In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from bs4 import BeautifulSoup
import re
import requests

In [ ]:
product_name=[]
distances=[]
emis=[]
#original_prices=[]
final_prices=[]
locations=[]

In [ ]:
req_header={
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/149.0.0.0 Safari/537.36",
    "Accept-Language": "en-GB,en-US;q=0.9,en;q=0.8",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
    "Referer": "https://www.google.com/"
    }
for i in range(1,1001):
    url=f"https://www.cars24.com/buy-used-car/?sort=bestmatch&serveWarrantyCount=true&listingSource=FilterTags&storeCityId={i}"
    #print(url)
    response=requests.get(url,headers=req_header)
    #print("Page :",i,response.status_code)
    html_data=response.text
    soup=BeautifulSoup(html_data)
    # Extract product name
    product=soup.find_all(class_='sc-ksBlki dxpZAa')
    for i in product:
      product_name.append(i.text)
    #Extract travalled distance
    distance=soup.find_all(class_='sc-ksBlki knJTXq')
    for i in distance:
      distances.append(i.text)
    #Extract emi
    emi=soup.find_all(class_='styles_flexItem__2z__J')
    for i in emi:
      emis.append(i.text)
    #Extract Original Price
    #original_price=soup.find_all(class_='sc-ksBlki fAywVv')
    #for i in original_price:
      #original_prices.append(i.text)
    #Extract Final Price
    final_price=soup.find_all(class_='sc-ksBlki dMXwkk')
    for i in final_price:
      final_prices.append(i.text)
    #Extract location
    location=soup.find_all(class_='styles_ellipsis__uatjG')
    for i in location:
      locations.append(i.text)

In [ ]:
km = [int(re.sub(r'[^0-9]', '', x)) for x in distances if re.search(r'km$', x)]
fuel = [x for x in distances if re.fullmatch(r'Petrol|Diesel|CNG|Electric|Hybrid', x)]
transmission = [x for x in distances if re.fullmatch(r'Manual|Automatic', x)]
registration = [x for x in distances if re.fullmatch(r'[A-Z]{2}-\d{1,2}', x)]

In [ ]:
print("Car Name:",product_name)
print("-"*150)
print("Kilometers:",km)
print("-"*150)
print("Fuel:",fuel)
print("-"*150)
print("Transmission:",transmission)
print("-"*150)
print("Registration:",registration)
print("-"*150)
print("EMI:",emis)
print("-"*150)
#print("Original Price:",original_prices)
#print("-"*150)
print("Final Price:",final_prices)
print("-"*150)
print("Location:",locations)

Car Name: ['2015 Hyundai Eon', '2019 Maruti Swift', '2015 Maruti Wagon R 1.0', '2015 Honda Amaze', '2019 Maruti Swift', '2016 Tata Tiago', '2019 Datsun Redi Go', '2019 Maruti Swift', '2020 Tata Tiago', '2015 Honda City', '2018 Datsun Redi Go', '2021 Tata PUNCH', '2017 Maruti Wagon R 1.0', '2019 Hyundai Grand i10', '2016 Hyundai Verna', '2019 MG HECTOR', '2017 Maruti Swift', '2017 Maruti Swift', '2016 Hyundai Creta', '2014 Hyundai Grand i10', '2023 Toyota Glanza', '2015 Maruti Swift', '2021 Maruti Swift', '2017 Renault Kwid', '2019 Ford FREESTYLE', '2022 Maruti Swift', '2017 Renault Kwid', '2016 Maruti Swift', '2019 Tata NEXON', '2022 Tata PUNCH', '2021 Renault Kwid', '2017 Maruti Wagon R 1.0', '2018 Renault Kwid', '2023 Tata PUNCH', '2022 Tata NEXON', '2012 Maruti Alto 800', '2019 Maruti Baleno', '2020 Renault TRIBER', '2018 Hyundai Grand i10', '2016 Hyundai Creta', '2015 Maruti Swift', '2017 Renault Kwid', '2022 Maruti Swift', '2019 Tata NEXON', '2023 Tata PUNCH', '2022 Tata NEXON', '2012 Maruti Alto 800', '2019 Maruti Baleno', '2018 Hyundai Grand i10', '2015 Volkswagen Polo', '2018 Toyota Innova Crysta', '2016 Ford Ecosport', '2018 Toyota YARIS', '2022 Skoda KUSHAQ', '2023 Mahindra SCORPIO CLASSIC', '2019 Tata NEXON', '2022 Mahindra Thar', '2022 Skoda SLAVIA', '2019 Volkswagen Polo', '2021 Nissan MAGNITE', '2023 Toyota Glanza', '2021 Maruti Swift', '2019 Ford FREESTYLE', '2015 Hyundai Eon', '2017 Renault Kwid', '2016 Maruti Swift', '2019 Maruti Swift', '2015 Maruti Wagon R 1.0', '2022 Tata PUNCH', '2015 Honda Amaze', '2021 Renault Kwid', '2017 Maruti Wagon R 1.0', '2019 Maruti Swift', '2018 Renault Kwid', '2016 Tata Tiago', '2019 Datsun Redi Go', '2019 Maruti Swift', '2020 Tata Tiago', '2015 Honda City', '2018 Datsun Redi Go', '2018 Maruti Wagon R 1.0', '2016 Renault Kwid', '2012 Maruti Alto 800', '2020 Maruti Alto', '2012 Honda City', '2016 Maruti Swift Dzire', '2020 Hyundai GRAND I10 NIOS', '2020 Maruti New Wagon-R', '2016 Maruti Swift', '2019 Ford Figo Aspire', '2024 Hyundai AURA', '2021 Renault Kiger', '2020 Maruti Vitara Brezza', '2022 Maruti IGNIS', '2022 Hyundai GRAND I10 NIOS', '2017 Honda WR-V', '2021 Toyota Fortuner', '2020 KIA SELTOS', '2024 KIA CARENS', '2017 Maruti Vitara Brezza', '2016 Maruti Swift', '2013 Maruti Wagon R 1.0', '2013 Hyundai Santro Xing', '2016 Maruti Swift', '2020 Tata NEXON', '2021 Maruti New Wagon-R', '2021 Maruti Dzire', '2021 Tata ALTROZ', '2017 Tata Tiago', '2016 Maruti Swift Dzire', '2014 Volkswagen Polo', '2016 Hyundai Eon', '2023 Hyundai AURA', '2016 Maruti Wagon R 1.0', '2015 Maruti Swift Dzire', '2017 Maruti Swift', '2018 Maruti Wagon R 1.0', '2016 Maruti Swift Dzire', '2021 KIA SONET', '2014 Maruti Alto K10', '2022 Maruti Ciaz', '2023 Tata PUNCH', '2021 Tata ALTROZ', '2016 Hyundai Elite i20', '2011 Maruti Wagon R 1.0', '2013 Maruti Ertiga', '2021 Renault Kiger', '2021 Skoda KUSHAQ', '2012 Maruti Swift Dzire', '2019 Hyundai Verna', '2015 Hyundai Eon', '2012 Honda City', '2013 Renault Duster', '2015 Maruti Wagon R 1.0', '2012 Maruti Wagon R 1.0', '2015 Hyundai i10', '2015 Maruti Wagon R 1.0', '2013 Hyundai i20', '2017 Maruti Vitara Brezza', '2024 Tata PUNCH', '2022 Maruti Alto', '2012 Maruti Wagon R 1.0', '2013 Maruti Wagon R 1.0', '2012 Hyundai i10', '2013 Hyundai Grand i10', '2014 Maruti Alto 800', '2012 Maruti Swift', '2017 Tata Tiago', '2015 Hyundai Eon', '2016 Renault Kwid', '2011 Ford Figo', '2013 Maruti Swift Dzire', '2016 Renault Kwid', '2021 Honda Amaze', '2017 Honda City', '2023 Hyundai VENUE', '2015 Hyundai i10', '2012 Toyota Etios', '2017 Hyundai Elite i20', '2023 Toyota Glanza', '2015 Maruti Swift', '2021 Maruti Swift', '2017 Renault Kwid', '2019 Ford FREESTYLE', '2015 Hyundai Eon', '2022 Maruti Swift', '2017 Renault Kwid', '2016 Maruti Swift', '2019 Tata NEXON', '2019 Maruti Swift', '2015 Maruti Wagon R 1.0', '2022 Tata PUNCH', '2015 Honda Amaze', '2021 Renault Kwid', '2017 Maruti Wagon R 1.0', '2019 Maruti Swift', '2018 Renault Kwid', '2023 Tata PUNCH', '2016 Tata Tiago', '2017 Tata TIGOR', '2016 Renault Duster', '2020 Hyundai Creta', '2022 Tata ALTROZ', '2011 Hyundai i20', '2015 Hyundai Grand i10', '2017 Tata Zest', '2016 Maruti Alto 800', '2012 Maruti Wagon R 1.0', '2020 Maruti Alto', '2016 Maruti Alto 800', '2015 Hyundai Grand i10', '2023 Volkswagen VIRTUS', '2017 Renault Kwid', '2012 Hyundai i10', '2014 Maruti Alto K10', '2014 Toyota Etios', '2013 Hyundai i20', '2020 KIA SELTOS', '2015 Renault Duster', '2012 Maruti Ritz', '2012 Renault Duster', '2023 Hyundai Verna', '2017 Hyundai Creta', '2014 Hyundai i20', '2011 Hyundai i10', '2014 Honda Mobilio', '2017 Mahindra XUV500', '2020 Maruti Alto', '2022 Renault TRIBER', '2012 Nissan Micra', '2015 Jaguar XF', '2024 Maruti BREZZA', '2018 Renault Duster', '2020 KIA SELTOS', '2023 Mahindra SCORPIO-N', '2011 Audi Q7', '2017 Toyota Fortuner', '2018 Toyota Fortuner', '2013 Maruti Ritz', '2021 Honda Amaze', '2015 Renault Kwid', '2020 Hyundai Creta', '2013 Maruti Wagon R 1.0', '2011 Maruti Wagon R 1.0', '2025 Hyundai NEW I20', '2017 Maruti Vitara Brezza', '2013 Nissan Terrano', '2018 Maruti Vitara Brezza', '2013 Hyundai Eon', '2017 Tata NEXON', '2018 Tata TIGOR', '2013 Maruti Ritz', '2020 Hyundai Elite i20', '2017 Honda WR-V', '2021 MG HECTOR PLUS', '2021 Jeep Compass', '2018 Maruti Wagon R 1.0', '2019 Maruti Baleno', '2023 Maruti Baleno', '2021 Tata Tiago', '2016 Ford Figo Aspire', '2021 Tata NEXON', '2014 Honda Amaze', '2017 Hyundai Elite i20', '2021 Tata Tiago', '2020 Maruti S PRESSO', '2020 Tata Tiago', '2021 Hyundai GRAND I10 NIOS', '2019 Tata NEXON', '2023 MG ASTOR', '2019 Honda Amaze', '2016 Maruti Alto 800', '2017 Maruti Baleno', '2022 Nissan MAGNITE', '2014 Hyundai Grand i10', '2018 Hyundai Grand i10', '2023 KIA SELTOS', '2015 Volkswagen Polo', '2011 Toyota Etios', '2014 Toyota Innova', '2016 Maruti Vitara Brezza', '2020 Hyundai VENUE', '2016 Renault Kwid', '2019 Renault Kwid', '2015 Maruti Wagon R 1.0', '2015 Maruti Wagon R 1.0', '2012 Hyundai New Elantra', '2021 Maruti XL6', '2012 Volkswagen Polo', '2020 Hyundai GRAND I10 NIOS', '2021 MG HECTOR PLUS', '2016 Maruti Swift', '2017 Volvo S60', '2014 Hyundai Santro Xing', '2014 Datsun Go', '2018 Renault Kwid', '2013 Maruti Swift Dzire', '2011 Chevrolet Aveo', '2020 Maruti Swift', '2012 Maruti Swift', '2012 Maruti Swift Dzire', '2013 Honda Brio', '2012 Maruti Swift Dzire', '2023 Tata PUNCH', '2013 Hyundai Eon', '2020 Mahindra Bolero', '2017 Maruti Ertiga', '2017 Maruti Swift', '2016 Hyundai Elite i20', '2011 Hyundai Verna', '2017 Renault Kwid', '2017 Hyundai Xcent', '2018 Maruti Wagon R 1.0', '2013 Maruti Swift Dzire', '2014 Hyundai Eon', '2019 Maruti Vitara Brezza', '2012 Maruti Wagon R 1.0', '2012 Maruti Swift Dzire', '2016 Maruti Alto 800', '2012 Hyundai i20', '2018 Renault Kwid', '2015 Maruti Swift', '2024 Tata NEXON', '2012 Maruti Wagon R 1.0', '2023 MG ASTOR', '2012 Maruti Wagon R 1.0', '2012 Maruti Wagon R 1.0', '2015 Renault Kwid', '2018 Honda Amaze', '2019 Tata Tiago', '2018 Maruti Celerio', '2013 Maruti Swift Dzire', '2013 Hyundai Eon', '2013 Hyundai Eon', '2016 Hyundai Grand i10', '2020 Maruti Baleno', '2014 Mahindra Bolero', '2016 Maruti Vitara Brezza', '2013 Mahindra XUV500', '2024 Hyundai VENUE', '2014 Hyundai i10', '2020 Datsun Redi Go', '2017 Maruti Vitara Brezza', '2020 Tata Harrier', '2019 Maruti Ertiga', '2017 Mahindra Kuv100', '2015 Maruti Ertiga', '2014 Nissan Terrano', '2020 Hyundai Creta', '2017 Mahindra Scorpio', '2021 Hyundai NEW SANTRO', '2022 Mahindra XUV700', '2016 Mahindra TUV300', '2016 Volkswagen Ameo', '2024 Hyundai AURA', '2020 Renault TRIBER', '2023 Honda Amaze', '2015 Maruti Swift Dzire', '2021 Maruti New Wagon-R', '2019 Maruti Eeco', '2013 Tata Indica EV2', '2017 Maruti Vitara Brezza', '2021 Honda WR-V', '2024 Tata PUNCH', '2012 Maruti Wagon R 1.0', '2014 Hyundai Eon', '2012 Maruti Wagon R 1.0', '2015 Hyundai Eon', '2015 Maruti Alto 800', '2018 Hyundai Grand i10', '2013 Hyundai i20', '2016 Tata Zest', '2021 Maruti Dzire', '2016 Renault Kwid', '2022 Maruti S PRESSO', '2020 Hyundai AURA', '2017 Maruti Dzire', '2019 Hyundai GRAND I10 NIOS', '2013 Renault Duster', '2012 Chevrolet Beat', '2021 Nissan MAGNITE', '2017 Hyundai Grand i10', '2016 Maruti Swift Dzire', '2013 Maruti Swift Dzire', '2013 Tata Safari Storme', '2013 Hyundai Eon', '2013 Volkswagen Polo', '2016 Maruti Wagon R 1.0', '2017 Maruti Swift', '2018 Maruti Swift', '2012 Hyundai i10', '2017 Mahindra KUV 100 NXT', '2013 Hyundai i20', '2015 Honda City', '2018 Honda Amaze', '2020 Mahindra Bolero', '2020 Tata ALTROZ', '2020 Maruti Baleno', '2016 Tata Safari Storme', '2015 Hyundai Creta', '2017 Maruti Ertiga', '2015 Hyundai Grand i10', '2016 Renault Duster', '2015 Hyundai i20 Active', '2023 Hyundai VENUE', '2017 Renault Kwid', '2015 Maruti Wagon R 1.0', '2025 Maruti Swift', '2022 Hyundai Verna', '2020 Maruti Dzire', '2021 Hyundai ALCAZAR', '2018 Maruti Swift', '2014 Maruti Ertiga', '2015 Maruti Celerio', '2016 Hyundai Verna', '2012 Maruti Zen Estilo', '2020 Maruti Dzire', '2015 Mahindra XUV500', '2013 Renault Duster', '2014 Maruti Wagon R 1.0', '2015 Hyundai i10', '2015 Maruti S Cross', '2016 Maruti Alto 800', '2019 Maruti Alto 800', '2018 Tata Tiago', '2014 Hyundai i10', '2013 Maruti Wagon R 1.0', '2022 Maruti New Wagon-R', '2022 Hyundai Verna', '2015 Renault Duster', '2017 Toyota Etios', '2024 Renault TRIBER', '2022 Mahindra XUV700', '2021 Hyundai Creta', '2023 Mahindra XUV300', '2022 Mahindra XUV700', '2021 KIA SELTOS', '2020 MG HECTOR', '2016 Maruti Swift', '2020 Volkswagen Vento', '2024 Volkswagen VIRTUS', '2015 Maruti Wagon R 1.0', '2020 Maruti Swift', '2015 Hyundai Grand i10', '2023 Maruti Celerio', '2014 Volkswagen Polo', '2020 Tata Tiago', '2023 KIA SELTOS', '2014 Maruti Alto 800', '2015 Maruti Wagon R 1.0', '2018 Hyundai Eon', '2016 Renault Kwid', '2018 Ford Figo Aspire', '2015 Maruti Celerio', '2017 Mahindra Kuv100', '2012 Hyundai i10', '2017 Maruti Wagon R 1.0', '2017 Maruti Baleno', '2018 Renault Kwid', '2013 Skoda Rapid', '2017 Honda City', '2018 Maruti Alto K10', '2015 Maruti Swift Dzire', '2011 Chevrolet Spark', '2016 Hyundai Elite i20', '2012 Hyundai i10', '2013 Hyundai Verna', '2016 Hyundai Elite i20', '2014 Datsun Go', '2013 Ford Figo', '2017 Maruti Baleno', '2013 Hyundai i10', '2014 Hyundai Eon', '2011 Hyundai Verna', '2015 Renault Duster', '2013 Volkswagen Polo', '2013 Maruti Alto K10', '2018 Mahindra XUV500', '2020 Skoda Rapid', '2013 Honda City', '2021 Maruti Alto', '2020 Hyundai VENUE', '2016 Renault Kwid', '2019 Renault Kwid', '2015 Maruti Wagon R 1.0', '2015 Maruti Wagon R 1.0', '2016 Hyundai Elite i20', '2016 Maruti Alto K10', '2014 Hyundai Elite i20', '2015 Maruti Alto K10', '2019 Renault TRIBER', '2015 Maruti Ertiga', '2023 Tata NEXON', '2015 Honda City', '2019 Honda Amaze', '2014 Ford Ecosport', '2023 Nissan MAGNITE', '2019 Honda Amaze', '2023 Tata NEXON', '2017 Mahindra XUV500', '2023 Maruti Ertiga', '2015 Hyundai Grand i10', '2022 Mahindra XUV700', '2015 Tata Zest', '2015 Mahindra XUV500', '2018 Honda City', '2014 Volkswagen Polo', '2014 Toyota Fortuner', '2016 Maruti Baleno', '2015 Hyundai Elite i20', '2012 Mahindra XUV500', '2011 Ford Figo', '2011 Maruti Swift', '2013 Hyundai i20', '2020 KIA SELTOS', '2017 Maruti Celerio', '2014 Maruti Swift Dzire', '2010 Chevrolet Cruze', '2016 Maruti Swift', '2014 Maruti Swift Dzire', '2020 Maruti S PRESSO', '2016 Honda City', '2011 Volkswagen Vento', '2020 Maruti Vitara Brezza', '2012 Maruti Wagon R 1.0', '2012 Maruti Wagon R 1.0', '2024 Hyundai Creta', '2023 Maruti Grand Vitara', '2021 MG HECTOR PLUS', '2022 Tata PUNCH', '2017 Maruti S Cross', '2018 Hyundai Grand i10', '2014 Hyundai Elite i20', '2011 BMW X1', '2018 Hyundai Creta', '2014 Fiat Grand Punto', '2011 Hyundai Verna', '2012 Hyundai Verna', '2015 Hyundai i10', '2016 Maruti Celerio', '2012 Hyundai Verna', '2020 Hyundai VENUE', '2016 Renault Kwid', '2019 Renault Kwid', '2015 Maruti Wagon R 1.0', '2015 Maruti Wagon R 1.0', '2016 Hyundai Elite i20', '2016 Maruti Alto K10', '2014 Hyundai Elite i20', '2015 Maruti Alto K10', '2019 Renault TRIBER', '2015 Maruti Ertiga', '2023 Tata NEXON', '2015 Honda City', '2019 Honda Amaze', '2014 Ford Ecosport', '2023 Nissan MAGNITE', '2019 Honda Amaze', '2023 Tata NEXON', '2017 Mahindra XUV500', '2023 Maruti Ertiga', '2018 Maruti Alto K10', '2016 Maruti Vitara Brezza', '2015 Hyundai Xcent', '2015 Maruti Swift Dzire', '2011 Chevrolet Spark', '2016 Hyundai Elite i20', '2016 Honda Amaze', '2012 Hyundai i10', '2019 Hyundai VENUE', '2013 Hyundai Verna', '2014 Maruti Alto K10', '2022 Tata ALTROZ', '2016 Hyundai Elite i20', '2014 Datsun Go', '2013 Ford Figo', '2017 Maruti Baleno', '2012 Maruti Alto K10', '2013 Chevrolet Beat', '2015 Maruti Wagon R 1.0', '2013 Hyundai i10', '2015 Maruti Swift', '2017 Renault Kwid', '2022 Maruti Swift', '2019 Tata NEXON', '2023 Tata PUNCH', '2022 Tata NEXON', '2012 Maruti Alto 800', '2019 Maruti Baleno', '2018 Hyundai Grand i10', '2015 Volkswagen Polo', '2018 Toyota Innova Crysta', '2016 Ford Ecosport', '2018 Toyota YARIS', '2022 Skoda KUSHAQ', '2023 Mahindra SCORPIO CLASSIC', '2019 Tata NEXON', '2022 Mahindra Thar', '2022 Skoda SLAVIA', '2019 Volkswagen Polo', '2021 Nissan MAGNITE', '2023 Toyota Glanza', '2021 Maruti Swift', '2019 Ford FREESTYLE', '2015 Hyundai Eon', '2017 Renault Kwid', '2016 Maruti Swift', '2019 Maruti Swift', '2015 Maruti Wagon R 1.0', '2022 Tata PUNCH', '2015 Honda Amaze', '2021 Renault Kwid', '2017 Maruti Wagon R 1.0', '2019 Maruti Swift', '2018 Renault Kwid', '2016 Tata Tiago', '2019 Datsun Redi Go', '2019 Maruti Swift', '2020 Tata Tiago', '2015 Honda City', '2018 Datsun Redi Go', '2018 Maruti Wagon R 1.0', '2016 Renault Kwid', '2012 Maruti Alto 800', '2020 Maruti Alto', '2012 Honda City', '2016 Maruti Swift Dzire', '2020 Hyundai GRAND I10 NIOS', '2020 Maruti New Wagon-R', '2016 Maruti Swift', '2019 Ford Figo Aspire', '2024 Hyundai AURA', '2021 Renault Kiger', '2020 Maruti Vitara Brezza', '2022 Maruti IGNIS', '2022 Hyundai GRAND I10 NIOS', '2017 Honda WR-V', '2021 Toyota Fortuner', '2020 KIA SELTOS', '2024 KIA CARENS', '2017 Maruti Vitara Brezza', '2016 Maruti Swift', '2013 Maruti Wagon R 1.0', '2013 Hyundai Santro Xing', '2016 Maruti Swift', '2020 Tata NEXON', '2021 Maruti New Wagon-R', '2021 Maruti Dzire', '2021 Tata ALTROZ', '2017 Tata Tiago', '2016 Maruti Swift Dzire', '2014 Volkswagen Polo', '2016 Hyundai Eon', '2023 Hyundai AURA', '2016 Maruti Wagon R 1.0', '2015 Maruti Swift Dzire', '2017 Maruti Swift', '2018 Maruti Wagon R 1.0', '2016 Maruti Swift Dzire', '2021 KIA SONET', '2017 Tata TIGOR', '2016 Renault Duster', '2020 Hyundai Creta', '2022 Tata ALTROZ', '2011 Hyundai i20', '2015 Hyundai Grand i10', '2017 Tata Zest', '2016 Maruti Alto 800', '2012 Maruti Wagon R 1.0', '2020 Maruti Alto', '2016 Maruti Alto 800', '2015 Hyundai Grand i10', '2023 Volkswagen VIRTUS', '2017 Renault Kwid', '2012 Hyundai i10', '2014 Maruti Alto K10', '2014 Toyota Etios', '2013 Hyundai i20', '2020 KIA SELTOS', '2015 Renault Duster', '2012 Maruti Ritz', '2012 Renault Duster', '2023 Hyundai Verna', '2017 Hyundai Creta', '2014 Hyundai i20', '2011 Hyundai i10', '2014 Honda Mobilio', '2017 Mahindra XUV500', '2020 Maruti Alto', '2022 Renault TRIBER', '2012 Nissan Micra', '2015 Jaguar XF', '2024 Maruti BREZZA', '2018 Renault Duster', '2020 KIA SELTOS', '2023 Mahindra SCORPIO-N', '2011 Audi Q7', '2017 Toyota Fortuner', '2018 Toyota Fortuner', '2013 Maruti Ritz', '2017 Maruti Wagon R 1.0', '2013 Volkswagen Polo', '2011 Maruti Wagon R 1.0', '2022 Maruti Ciaz', '2019 Hyundai GRAND I10 NIOS', '2019 Honda Amaze', '2016 Maruti Swift Dzire', '2018 Tata TIAGO NRG', '2015 Toyota Corolla', '2013 Honda Amaze', '2024 Maruti Ertiga', '2015 Maruti Wagon R 1.0', '2022 Maruti Baleno', '2020 Maruti Baleno', '2023 Tata NEXON', '2020 Maruti Alto', '2016 Maruti Wagon R 1.0', '2019 Renault Kwid', '2013 Hyundai Santro Xing', '2016 Ford Figo Aspire', '2019 Hyundai VENUE', '2022 Tata ALTROZ', '2016 Maruti Swift', '2014 Datsun Go', '2013 Hyundai Eon', '2015 Hyundai i10', '2013 Maruti Alto 800', '2019 Maruti Swift', '2013 Hyundai i20', '2021 KIA SONET', '2018 Renault Kwid', '2018 Hyundai Verna', '2021 Maruti IGNIS', '2017 Honda Jazz', '2015 Maruti Baleno', '2015 Renault Duster', '2015 Mahindra Thar', '2022 Renault TRIBER', '2016 Maruti Celerio', '2017 Maruti Ciaz', '2020 Hyundai VENUE', '2016 Renault Kwid', '2019 Renault Kwid', '2015 Maruti Wagon R 1.0', '2015 Maruti Wagon R 1.0', '2016 Hyundai Elite i20', '2016 Maruti Alto K10', '2014 Hyundai Elite i20', '2015 Maruti Alto K10', '2019 Renault TRIBER', '2015 Maruti Ertiga', '2023 Tata NEXON', '2015 Honda City', '2019 Honda Amaze', '2014 Ford Ecosport', '2023 Nissan MAGNITE', '2019 Honda Amaze', '2023 Tata NEXON', '2017 Mahindra XUV500', '2023 Maruti Ertiga', '2021 Maruti Swift', '2017 Renault Kwid', '2016 Maruti Swift', '2018 Renault Kwid', '2017 Hyundai Creta', '2018 Hyundai Grand i10', '2015 Maruti Swift Dzire', '2023 Tata PUNCH', '2020 Renault TRIBER', '2023 KIA CARENS', '2016 Toyota Corolla Altis', '2015 Maruti Alto 800', '2017 Datsun Redi Go', '2023 Toyota URBAN CRUISER HYRYDER', '2021 Maruti New Wagon-R', '2015 Hyundai i10', '2023 Honda Amaze', '2019 Renault Kwid', '2016 Ford Ecosport', '2019 Renault TRIBER', '2023 Toyota Glanza', '2015 Maruti Swift', '2017 Renault Kwid', '2019 Ford FREESTYLE', '2015 Hyundai Eon', '2022 Maruti Swift', '2019 Tata NEXON', '2019 Maruti Swift', '2015 Maruti Wagon R 1.0', '2022 Tata PUNCH', '2015 Honda Amaze', '2021 Renault Kwid', '2017 Maruti Wagon R 1.0', '2019 Maruti Swift', '2023 Tata PUNCH', '2016 Tata Tiago', '2019 Datsun Redi Go', '2019 Maruti Swift', '2022 Tata NEXON', '2020 Tata Tiago', '2014 Maruti Wagon R 1.0', '2016 Mahindra TUV300', '2020 Maruti S Cross', '2015 Toyota Corolla Altis', '2020 Tata ALTROZ', '2016 Renault Kwid', '2022 Tata PUNCH', '2012 Maruti Wagon R 1.0', '2012 Maruti Wagon R 1.0', '2012 Maruti Wagon R 1.0', '2012 Maruti Wagon R 1.0', '2012 Maruti Wagon R 1.0', '2012 Maruti Swift Dzire', '2013 Maruti Swift Dzire', '2017 Honda City', '2015 Maruti Wagon R 1.0', '2016 Maruti Swift', '2012 Maruti Swift Dzire', '2013 Maruti Swift Dzire', '2018 Maruti Swift', '2012 Maruti Wagon R 1.0', '2012 Maruti Swift Dzire', '2016 Maruti Alto 800', '2012 Hyundai i20', '2018 Renault Kwid', '2015 Maruti Swift', '2024 Tata NEXON', '2012 Maruti Wagon R 1.0', '2023 MG ASTOR', '2012 Maruti Wagon R 1.0', '2012 Maruti Wagon R 1.0', '2015 Renault Kwid', '2018 Honda Amaze', '2019 Tata Tiago', '2018 Maruti Celerio', '2013 Maruti Swift Dzire', '2013 Hyundai Eon', '2013 Hyundai Eon', '2016 Hyundai Grand i10', '2020 Maruti Baleno', '2015 Hyundai Grand i10', '2016 Renault Duster', '2015 Hyundai i20 Active', '2023 Hyundai VENUE', '2017 Renault Kwid', '2015 Maruti Wagon R 1.0', '2025 Maruti Swift', '2022 Hyundai Verna', '2020 Maruti Dzire', '2021 Hyundai ALCAZAR', '2018 Maruti Swift', '2014 Maruti Ertiga', '2015 Maruti Celerio', '2016 Hyundai Verna', '2012 Maruti Zen Estilo', '2020 Maruti Dzire', '2015 Mahindra XUV500', '2013 Renault Duster', '2014 Maruti Wagon R 1.0', '2015 Hyundai i10', '2014 Honda City', '2016 Maruti Swift', '2014 Maruti Swift', '2015 Fiat Linea', '2019 Maruti Alto K10', '2017 Tata Zest', '2014 Maruti Wagon R 1.0', '2017 Hyundai Elite i20', '2019 Mahindra Scorpio', '2023 Tata Harrier', '2020 Mahindra XUV300', '2022 Renault TRIBER', '2014 Datsun Go', '2018 Hyundai Verna', '2012 Chevrolet Beat', '2015 Audi Q3', '2013 Ford Ecosport', '2021 Toyota Innova Crysta', '2014 Hyundai Grand i10', '2017 Hyundai Grand i10', '2018 Hyundai Grand i10', '2014 Mahindra Quanto', '2022 Tata Harrier', '2019 Tata NEXON', '2024 KIA SELTOS', '2021 Maruti Swift', '2022 Mahindra XUV700', '2014 Maruti Wagon R 1.0', '2018 Maruti Vitara Brezza', '2013 Maruti Wagon R 1.0', '2012 Maruti Wagon R 1.0', '2012 Maruti Wagon R 1.0', '2012 Maruti Wagon R 1.0', '2014 Maruti Wagon R 1.0', '2012 Maruti Alto 800', '2012 Maruti Wagon R 1.0', '2015 Hyundai Eon', '2013 Hyundai Eon', '2012 Maruti Wagon R 1.0', '2013 Maruti Wagon R 1.0', '2013 Hyundai Eon', '2012 Hyundai i10

In [ ]:
print("Car Name:",len(product_name))
print("-"*150)
print("Kilometers:",len(km))
print("-"*150)
print("Fuel:",len(fuel))
print("-"*150)
print("Transmission:",len(transmission))
print("-"*150)
print("Registration:",len(registration))
print("-"*150)
print("EMI:",len(emis))
print("-"*150)
#print("Original Price:",len(original_prices))
#print("-"*150)
print("Final Price:",len(final_prices))
print("-"*150)
print("Location:",len(locations))

Car Name: 1123
------------------------------------------------------------------------------------------------------------------------------------------------------
Kilometers: 1123
------------------------------------------------------------------------------------------------------------------------------------------------------
Fuel: 1123
------------------------------------------------------------------------------------------------------------------------------------------------------
Transmission: 1036
------------------------------------------------------------------------------------------------------------------------------------------------------
Registration: 1009
------------------------------------------------------------------------------------------------------------------------------------------------------
EMI: 5796
------------------------------------------------------------------------------------------------------------------------------------------------------
Final Price: 1755
------------------------------------------------------------------------------------------------------------------------------------------------------
Location: 2898

In [ ]:
min_len_list=[
    len(product_name),
    len(emis),
    len(km),
    len(fuel),
    len(transmission),
    len(registration),
    #len(original_prices),
    len(final_prices),
    len(locations) ]
min_len = min(min_len_list)
print(min_len)
df=pd.DataFrame({
    "Car Name":product_name[:min_len],
    "Kilometers":km[:min_len],
    "Fuel":fuel[:min_len],
    "Transmission":transmission[:min_len],
    "Registration":registration[:min_len],
    "EMI":emis[:min_len],
    #"Original Price":original_prices[:min_len],
    "Final Price":final_prices[:min_len],
    "Location":locations[:min_len]
})
df.shape

1009

(1009, 8)

In [ ]:
df.head()

,Car Name,Kilometers,Fuel,Transmission,Registration,EMI,Final Price,Location
0,2015 Hyundai Eon,43518,Petrol,Manual,DL-11,"EMI ₹8,826/m*",Account,"Piyush Mahendra Mall, opp. Dussehra Ground, N..."
1,2019 Maruti Swift,58358,CNG,Manual,DL-13,₹5.64L₹5.00 lakh+ other charges,₹1.77 lakh,"M3M Urbana, Golf Course Ext., Gurugram"
2,2015 Maruti Wagon R 1.0,65974,CNG,Manual,DL-14,Not available on EMI,₹4.05 lakh,"Gaur City mall, Multilevel parking, Greater N..."
3,2015 Honda Amaze,40807,Petrol,Manual,HR-21,₹3.81L₹3.13 lakh+ other charges,₹2.13 lakh,"M3M Urbana, Golf Course Ext., Gurugram"
4,2019 Maruti Swift,57241,Petrol,Manual,DL-10,"EMI ₹8,120/m*",₹2.35 lakh,"GNB Mall, Raj Nagar Extension, Ghaziabad"

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df['Car Name'].value_counts()

Car Name
2015 Maruti Wagon R 1.0    27
2012 Maruti Wagon R 1.0    26
2016 Maruti Swift          19
2019 Maruti Swift          16
2017 Renault Kwid          15
                           ..
2024 Maruti Ertiga          1
2013 Maruti Alto 800        1
2021 Maruti IGNIS           1
2017 Honda Jazz             1
2013 Chevrolet Sail         1
Name: count, Length: 339, dtype: int64

In [ ]:
df['EMI'].value_counts()

EMI
Not available on EMI               43
EMI ₹6,443/m*                       7
EMI ₹8,120/m*                       7
₹4.25L₹4.15 lakh+ other charges     6
₹4.40L₹4.05 lakh+ other charges     6
                                   ..
EMI ₹7,488/m*                       1
₹3.83 lakh                          1
EMI ₹9,197/m*                       1
₹5.33L₹5.21 lakh+ other charges     1
EMI ₹3,581/m*                       1
Name: count, Length: 658, dtype: int64

In [ ]:
df.to_csv('car_data.csv', index=False)
print("DataFrame saved to 'car_data.csv'")

from google.colab import files
files.download('car_data.csv')

DataFrame saved to 'car_data.csv'